sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
after_script:
  - cd ./public
  - git init
  - git config user.name "Luyc"
  - git config user.email "flyingedwardlu@gmail.com"
  - git add .
  - git commit -a -m "Auto update docs by Travis CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - workspace

env:
 global:
   - GH_REF: github.com/luyc/luyc.github.io.git